version: '2'
services:
  logger:
    build: ./deploy/log/
    restart: always
    volumes:
      - /var/log/yiizh.com/:/var/log/docker/
    ports:
      - 10100:514
  frontend:
    image: yiizh/yiizh.com:latest
    ports:
      - "127.0.0.1:10101:80"
    depends_on:
      - logger
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:10100"
        tag: "frontend"
    restart: always
    volumes:
      - /opt/composer/cache:/opt/composer/cache
      - /opt/apps/yiizh.com/uploads:/app/src/frontend/web/uploads
      - /opt/apps/yiizh.com/sitemaps:/app/src/frontend/web/sitemaps
    env_file: env.ini
    dns:
      - 223.5.5.5
      - 223.6.6.6
      - 8.8.8.8
      - 8.4.4.4
  crontab:
      image: yiizh/yiizh.com:latest
      depends_on:
        - logger
      logging:
        driver: "syslog"
        options:
          syslog-address: "tcp://127.0.0.1:10100"
          tag: "crontab"
      restart: always
      volumes:
        - /opt/composer/cache:/opt/composer/cache
        - /opt/apps/yiizh.com/uploads:/app/src/frontend/web/uploads
        - /opt/apps/yiizh.com/sitemaps:/app/src/frontend/web/sitemaps
      env_file: env.ini
      dns:
        - 223.5.5.5
        - 223.6.6.6
        - 8.8.8.8
        - 8.4.4.4
      command: ["php", "/app/bin/console","crontab/startup"]